# Generated by Django 5.0.2 on 2024-02-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Job',
        ),
        migrations.AlterModelOptions(
            name='cateogry',
            options={'verbose_name': 'Cateogry', 'verbose_name_plural': 'Cateogry'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'job', 'verbose_name_plural': 'job'},
        ),
    ]
